name: "Auto Assign"

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Auto-assign participants"
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: ".github/auto_assign.yml" # Path to your config file
